# Saneado de Datos

<p> Se solicita reparar los datos de un dataset, disponible en el aula virtual. 
No importa el lenguaje utilizado para repararlo. 
Dentro de los requisitos de saneamiento se pide: </p>

<ul><li>Generar un csv separado por comas</li>
<li>Que el carácter decimal sea el ‘.’ (punto)</li>
<li>Eliminar los caracteres extraños de longitud y latitud</li>
<li>Ponerle el símbolo de temperatura a todas las medidas</li>
<li>Comprobar que la media es la media aritmética de las temperaturas de los meses del año. En el caso que no sea correcta indicarlo en una columna adicional con un número que indique la desviación.</li>
</ul>

## Cargar Librerias

In [23]:
%matplotlib inline

import os
import pandas as pd
import numpy as np

## Generar CSV

In [24]:
ts = pd.read_csv('temperaturas.txt', sep = '\s+')
ts.rename(columns={'Septimbre':'Septiembre'}, inplace=True)
ts.to_csv('temperaturas.csv', index=False)
ts.head(10)

,Longitud,Latitud,Enero,Febrero,Marzo,Abril,Mayo,Junio,Julio,Agosto,Septiembre,Octubre,Noviembre,Diciembre,Media
0,"-179,750",71.2º50,"-23,0","-25,7","-24,3",-17.9,"-7,1","-0,1",1.8º,1.4,"-1,7",-8.2º,"-15,6º",-22.2º,"-11,6º"
1,"-179,750","68,750","-26,0","-28,7","-26,7","-20,0",-7.8º,"0,1","3,0","1,7",-1.9,-10.4,-18.2º,"-25,5","-13,3"
2,"-179,750",68.2º50,-25.9,"-27,6º",-25.9,"-19,3","-8,6º","0,0",2.9,"2,0",-1.8º,"-9,7","-17,5","-24,5",-12.9
3,"-179,750","67,750","-24,1","-25,0","-23,5","-17,1","-7,7",1.2º,"4,5",3.8º,-0.2º,"-7,6º","-15,3",-22.2º,"-11,0"
4,"-179,750",67.2º50,-24.8º,-24.8º,"-24,0",-17.4,"-9,1",-0.4,3.4,"3,0","-1,6º",-8.4,"-16,0",-22.4,"-11,7"
5,"-179,750","66,750","-21,0","-20,1","-20,3","-13,0",-5.8º,"2,6º","6,7",6.8º,1.4,"-5,0",-12.4,-18.2º,"-8,1"
6,"-179,750",66.2º50,-19.2º,-17.9,"-19,1","-11,0",-4.2º,3.9,8.2º,8.4,"2,5","-3,5","-11,0",-16.2º,"-6,5"
7,"-179,750","65,750",-17.9,"-17,5","-18,0",-10.2º,-2.8º,5.2º,"9,7","9,6º",3.9,-2.8º,"-10,5",-15.9,"-5,6º"
8,"-179,750",65.2º50,"-17,5",-18.2º,-17.9,-10.8º,"-2,3","5,3","10,1","9,5","4,1","-3,5",-11.2º,"-16,6º","-5,6º"
9,"-179,750","-16,750","27,0",27.2º,"27,0","26,7","26,1",25.4,24.8º,24.8º,"25,0","25,7",26.2º,"26,7","20,0"

## Cargar Dataset

In [25]:
ts = pd.read_csv('temperaturas.csv', sep = ',')
ts.head(10)

,Longitud,Latitud,Enero,Febrero,Marzo,Abril,Mayo,Junio,Julio,Agosto,Septiembre,Octubre,Noviembre,Diciembre,Media
0,"-179,750",71.2º50,"-23,0","-25,7","-24,3",-17.9,"-7,1","-0,1",1.8º,1.4,"-1,7",-8.2º,"-15,6º",-22.2º,"-11,6º"
1,"-179,750","68,750","-26,0","-28,7","-26,7","-20,0",-7.8º,"0,1","3,0","1,7",-1.9,-10.4,-18.2º,"-25,5","-13,3"
2,"-179,750",68.2º50,-25.9,"-27,6º",-25.9,"-19,3","-8,6º","0,0",2.9,"2,0",-1.8º,"-9,7","-17,5","-24,5",-12.9
3,"-179,750","67,750","-24,1","-25,0","-23,5","-17,1","-7,7",1.2º,"4,5",3.8º,-0.2º,"-7,6º","-15,3",-22.2º,"-11,0"
4,"-179,750",67.2º50,-24.8º,-24.8º,"-24,0",-17.4,"-9,1",-0.4,3.4,"3,0","-1,6º",-8.4,"-16,0",-22.4,"-11,7"
5,"-179,750","66,750","-21,0","-20,1","-20,3","-13,0",-5.8º,"2,6º","6,7",6.8º,1.4,"-5,0",-12.4,-18.2º,"-8,1"
6,"-179,750",66.2º50,-19.2º,-17.9,"-19,1","-11,0",-4.2º,3.9,8.2º,8.4,"2,5","-3,5","-11,0",-16.2º,"-6,5"
7,"-179,750","65,750",-17.9,"-17,5","-18,0",-10.2º,-2.8º,5.2º,"9,7","9,6º",3.9,-2.8º,"-10,5",-15.9,"-5,6º"
8,"-179,750",65.2º50,"-17,5",-18.2º,-17.9,-10.8º,"-2,3","5,3","10,1","9,5","4,1","-3,5",-11.2º,"-16,6º","-5,6º"
9,"-179,750","-16,750","27,0",27.2º,"27,0","26,7","26,1",25.4,24.8º,24.8º,"25,0","25,7",26.2º,"26,7","20,0"

## Que el caracter decimal sea el punto (.)

In [26]:
ts = ts.apply(lambda x: x.str.replace(',','.'))
ts.head(10)

,Longitud,Latitud,Enero,Febrero,Marzo,Abril,Mayo,Junio,Julio,Agosto,Septiembre,Octubre,Noviembre,Diciembre,Media
0,-179.750,71.2º50,-23.0,-25.7,-24.3,-17.9,-7.1,-0.1,1.8º,1.4,-1.7,-8.2º,-15.6º,-22.2º,-11.6º
1,-179.750,68.750,-26.0,-28.7,-26.7,-20.0,-7.8º,0.1,3.0,1.7,-1.9,-10.4,-18.2º,-25.5,-13.3
2,-179.750,68.2º50,-25.9,-27.6º,-25.9,-19.3,-8.6º,0.0,2.9,2.0,-1.8º,-9.7,-17.5,-24.5,-12.9
3,-179.750,67.750,-24.1,-25.0,-23.5,-17.1,-7.7,1.2º,4.5,3.8º,-0.2º,-7.6º,-15.3,-22.2º,-11.0
4,-179.750,67.2º50,-24.8º,-24.8º,-24.0,-17.4,-9.1,-0.4,3.4,3.0,-1.6º,-8.4,-16.0,-22.4,-11.7
5,-179.750,66.750,-21.0,-20.1,-20.3,-13.0,-5.8º,2.6º,6.7,6.8º,1.4,-5.0,-12.4,-18.2º,-8.1
6,-179.750,66.2º50,-19.2º,-17.9,-19.1,-11.0,-4.2º,3.9,8.2º,8.4,2.5,-3.5,-11.0,-16.2º,-6.5
7,-179.750,65.750,-17.9,-17.5,-18.0,-10.2º,-2.8º,5.2º,9.7,9.6º,3.9,-2.8º,-10.5,-15.9,-5.6º
8,-179.750,65.2º50,-17.5,-18.2º,-17.9,-10.8º,-2.3,5.3,10.1,9.5,4.1,-3.5,-11.2º,-16.6º,-5.6º
9,-179.750,-16.750,27.0,27.2º,27.0,26.7,26.1,25.4,24.8º,24.8º,25.0,25.7,26.2º,26.7,20.0

## Eliminación de Caracteres Extraños

In [27]:
ts = ts.apply(lambda x: x.str.replace('º',''))
ts.head(10)

,Longitud,Latitud,Enero,Febrero,Marzo,Abril,Mayo,Junio,Julio,Agosto,Septiembre,Octubre,Noviembre,Diciembre,Media
0,-179.750,71.250,-23.0,-25.7,-24.3,-17.9,-7.1,-0.1,1.8,1.4,-1.7,-8.2,-15.6,-22.2,-11.6
1,-179.750,68.750,-26.0,-28.7,-26.7,-20.0,-7.8,0.1,3.0,1.7,-1.9,-10.4,-18.2,-25.5,-13.3
2,-179.750,68.250,-25.9,-27.6,-25.9,-19.3,-8.6,0.0,2.9,2.0,-1.8,-9.7,-17.5,-24.5,-12.9
3,-179.750,67.750,-24.1,-25.0,-23.5,-17.1,-7.7,1.2,4.5,3.8,-0.2,-7.6,-15.3,-22.2,-11.0
4,-179.750,67.250,-24.8,-24.8,-24.0,-17.4,-9.1,-0.4,3.4,3.0,-1.6,-8.4,-16.0,-22.4,-11.7
5,-179.750,66.750,-21.0,-20.1,-20.3,-13.0,-5.8,2.6,6.7,6.8,1.4,-5.0,-12.4,-18.2,-8.1
6,-179.750,66.250,-19.2,-17.9,-19.1,-11.0,-4.2,3.9,8.2,8.4,2.5,-3.5,-11.0,-16.2,-6.5
7,-179.750,65.750,-17.9,-17.5,-18.0,-10.2,-2.8,5.2,9.7,9.6,3.9,-2.8,-10.5,-15.9,-5.6
8,-179.750,65.250,-17.5,-18.2,-17.9,-10.8,-2.3,5.3,10.1,9.5,4.1,-3.5,-11.2,-16.6,-5.6
9,-179.750,-16.750,27.0,27.2,27.0,26.7,26.1,25.4,24.8,24.8,25.0,25.7,26.2,26.7,20.0

### Cambio de tipos de datos como verificación de ausencia de valores extraños

In [28]:
#cambio de tipos de datos de columnas 
ts= ts.apply(lambda col:pd.to_numeric(col, errors='coerce'))
#ts['Media'] = ts['Media'].astype(np.float64)
#ts.dtypes
ts.describe()

,Longitud,Latitud,Enero,Febrero,Marzo,Abril,Mayo,Junio,Julio,Agosto,Septiembre,Octubre,Noviembre,Diciembre,Media
count,500.000000,500.000000,500.000000,500.00000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000
mean,-172.344000,-39.700000,-22.463200,-30.17560,-37.688600,-39.053600,-36.846600,-34.724400,-35.241200,-35.516400,-36.279800,-32.522800,-26.555600,-21.837600,-32.445200
std,4.765983,70.516087,7.266565,10.81431,16.999901,20.106463,23.819042,27.190899,29.639757,29.422667,27.765207,20.988076,13.111079,7.582066,19.025775
min,-179.750000,-89.750000,-29.200000,-41.30000,-54.600000,-58.100000,-58.300000,-58.800000,-60.300000,-60.300000,-60.200000,-51.600000,-39.500000,-29.200000,-54.000000
25%,-176.375000,-87.750000,-27.800000,-40.10000,-53.000000,-56.500000,-56.925000,-57.400000,-59.100000,-59.100000,-59.000000,-50.500000,-38.100000,-27.725000,-48.900000
50%,-172.750000,-85.750000,-24.000000,-33.55000,-45.150000,-49.250000,-50.250000,-50.250000,-53.250000,-53.450000,-52.900000,-44.250000,-32.950000,-23.800000,-42.900000
75%,-168.250000,64.750000,-19.875000,-22.07500,-19.250000,-16.775000,-7.200000,2.000000,5.500000,4.525000,1.625000,-5.300000,-12.675000,-17.775000,-9.200000
max,-164.250000,71.250000,27.400000,27.20000,27.000000,26.700000,26.100000,25.400000,25.200000,24.800000,25.400000,26.100000,26.500000,27.200000,26.100000

## Comprobación de Media Aritmética

In [29]:

ts['Media Real'] = ts[['Enero', 'Febrero','Marzo','Abril','Mayo','Junio','Julio',
                      'Agosto','Septiembre','Octubre','Noviembre','Diciembre']].mean(axis=1)
#axis = 1 means 'USE COLUMNS'
ts = ts.round({'Media Real':1})
ts['Diferencia'] = ts['Media'] - ts['Media Real']
tsx = ts
ts.to_csv('temperaturas_instance.csv', index=False, float_format='%.3f')
ts.to_json('temperaturas_complete_records.json',orient="records")
ts.head()

,Longitud,Latitud,Enero,Febrero,Marzo,Abril,Mayo,Junio,Julio,Agosto,Septiembre,Octubre,Noviembre,Diciembre,Media,Media Real,Diferencia
0,-179.75,71.25,-23.0,-25.7,-24.3,-17.9,-7.1,-0.1,1.8,1.4,-1.7,-8.2,-15.6,-22.2,-11.6,-11.9,0.3
1,-179.75,68.75,-26.0,-28.7,-26.7,-20.0,-7.8,0.1,3.0,1.7,-1.9,-10.4,-18.2,-25.5,-13.3,-13.4,0.1
2,-179.75,68.25,-25.9,-27.6,-25.9,-19.3,-8.6,0.0,2.9,2.0,-1.8,-9.7,-17.5,-24.5,-12.9,-13.0,0.1
3,-179.75,67.75,-24.1,-25.0,-23.5,-17.1,-7.7,1.2,4.5,3.8,-0.2,-7.6,-15.3,-22.2,-11.0,-11.1,0.1
4,-179.75,67.25,-24.8,-24.8,-24.0,-17.4,-9.1,-0.4,3.4,3.0,-1.6,-8.4,-16.0,-22.4,-11.7,-11.9,0.2

## Colocación de símbolo de temperatura

In [30]:
cols = ['Enero', 'Febrero','Marzo','Abril','Mayo','Junio','Julio',
                      'Agosto','Septiembre','Octubre','Noviembre','Diciembre','Media', 'Media Real', 'Diferencia']

tsx[cols] = ts[cols].round({'Diferencia':1}).astype(str) + "º"
tsx.head()

,Longitud,Latitud,Enero,Febrero,Marzo,Abril,Mayo,Junio,Julio,Agosto,Septiembre,Octubre,Noviembre,Diciembre,Media,Media Real,Diferencia
0,-179.75,71.25,-23.0º,-25.7º,-24.3º,-17.9º,-7.1º,-0.1º,1.8º,1.4º,-1.7º,-8.2º,-15.6º,-22.2º,-11.6º,-11.9º,0.3º
1,-179.75,68.75,-26.0º,-28.7º,-26.7º,-20.0º,-7.8º,0.1º,3.0º,1.7º,-1.9º,-10.4º,-18.2º,-25.5º,-13.3º,-13.4º,0.1º
2,-179.75,68.25,-25.9º,-27.6º,-25.9º,-19.3º,-8.6º,0.0º,2.9º,2.0º,-1.8º,-9.7º,-17.5º,-24.5º,-12.9º,-13.0º,0.1º
3,-179.75,67.75,-24.1º,-25.0º,-23.5º,-17.1º,-7.7º,1.2º,4.5º,3.8º,-0.2º,-7.6º,-15.3º,-22.2º,-11.0º,-11.1º,0.1º
4,-179.75,67.25,-24.8º,-24.8º,-24.0º,-17.4º,-9.1º,-0.4º,3.4º,3.0º,-1.6º,-8.4º,-16.0º,-22.4º,-11.7º,-11.9º,0.2º

## Guardar el Archivo saneado

In [31]:
tsx.to_csv('temperaturas_cleaned.csv', index=False)