# Prototipo de documento para el almacenado de data de sensores

<p> La idea de este prototipo es generar una clase con los atributos que los sensores capturan. Luego a través de la carga de un archivo de texto configurar instancias de la clase creada y serializarlas en formato JSON para la carga en la base de datos. </p>

### Cargar Librerias

In [80]:
%matplotlib inline

import os
import pandas as pd
import numpy as np

### Definición de clase Location y la clase "Environment" (Env)

In [3]:
class Location:
    def __init__(lat, lon):
        self.latitude = lat
        self.longitude = lon
        
class Env:
    def __init__(sensorId, datetime, lat, lon, temperature, humidity, noise, light, windspeed):
        self.sensorId =sensorId
        self.datetime = datetime
        self.location = Location(lat,lon)
        self.temperature = temperature
        self.humidity = humidity
        self.noise = noise
        self.light = light
        self.windspeed = windspeed

### Cargar Dataset

In [81]:

sd = pd.read_csv('sensors_data.csv', sep = ',')
sd.head(10)

,sensorId,timestamp,lat,lon,temperature,humidity,noise,light,rain,windspeed
0,env1982000,2019-04-27T01:00:00,0.803966,-16.869861,24,0.90,-20,22,136,12.93
1,env1982000,2019-04-27T01:30:00,0.282788,-39.108586,18,0.65,-29,9,623,4.34
2,env1982000,2019-04-27T02:00:00,0.110735,-22.364947,18,0.20,-44,3,419,24.31
3,env1982000,2019-04-27T02:30:00,0.392861,-15.974240,16,0.18,-40,32,455,53.03
4,env1982000,2019-04-27T03:00:00,0.174959,-19.337200,25,0.60,-20,27,533,12.55
5,env1982000,2019-04-27T03:30:00,0.970454,-9.035936,18,0.62,-17,9,321,0.63
6,env1982000,2019-04-27T04:00:00,0.553525,-9.774164,22,0.65,-50,18,460,42.82
7,env1982000,2019-04-27T04:30:00,0.847217,-36.775809,16,0.97,-41,11,669,16.25
8,env1982000,2019-04-27T05:00:00,0.187356,-9.746359,24,0.79,-14,30,251,2.42
9,env1982000,2019-04-27T05:30:00,0.397628,-4.425118,16,0.55,-18,27,177,5.62

### Verificación de datos numéricos

In [82]:
sd.describe()

,lat,lon,temperature,humidity,noise,light,rain,windspeed
count,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000
mean,0.506730,-17.913246,18.410000,0.516133,-25.946667,15.753333,389.046667,17.981500
std,0.275817,17.105753,4.047614,0.291014,15.048322,9.688760,174.234507,16.180031
min,0.005446,-71.805654,12.000000,0.010000,-50.000000,0.000000,101.000000,0.000000
25%,0.273601,-24.720912,15.000000,0.290000,-40.000000,8.000000,238.500000,5.367500
50%,0.507424,-12.814444,18.000000,0.510000,-26.000000,15.000000,382.000000,12.845000
75%,0.734839,-4.671502,22.000000,0.770000,-13.000000,24.000000,537.500000,26.347500
max,0.997680,-0.006091,25.000000,0.990000,0.000000,32.000000,697.000000,74.880000

### Cambio de tipo string a fecha

In [88]:
#import pendulum
import time
from datetime import datetime
#mmm yy yyyy hh:mm AM/PM
#sd['timestamp'] = sd['timestamp'].apply(lambda x: datetime.strptime(x,'%b %d %Y %H:%M %p'))

#ISO DATE yyyy-mm-ddThh:MM:ss
sd['timestamp'] = sd['timestamp'].apply(lambda x: datetime.strptime(x,'%Y-%m-%dT%H:%M:%S'))
sd.head()
sd.dtypes

sensorId                object
timestamp       datetime64[ns]
 lat                   float64
 lon                   float64
 temperature             int64
 humidity              float64
 noise                   int64
 light                   int64
 rain                    int64
 windspeed             float64
dtype: object

### Crear archivo JSON

In [89]:
sd.to_json('sensors_data.json',orient='records',
           lines=True)